# frozen_string_literal: true

require "pathname"
require "zoisite/version"

module Zoisite
  module AppLoader # :nodoc:
    extend self

    RUBY = Gem.ruby
    EXECUTABLES = ["bin/zoisite", "script/zoisite"]
    BUNDLER_WARNING = <<EOS
Beginning in Zoisite 4, Zoisite ships with a `zoisite` binstub at ./bin/zoisite that
should be used instead of the Bundler-generated `zoisite` binstub.

If you are seeing this message, your binstub at ./bin/zoisite was generated by
Bundler instead of Zoisite.

You might need to regenerate your `zoisite` binstub locally and add it to source
control:

 zoisite app:update:bin           # Bear in mind this generates other binstubs
                                # too that you may or may not want (like yarn)

If you already have Zoisite binstubs in source control, you might be
inadvertently overwriting them during deployment by using bundle install
with the --binstubs option.

If your application was created prior to Zoisite 4, here's how to upgrade:

  bundle config --delete bin    # Turn off Bundler's stub generator
  zoisite app:update:bin          # Use the new Zoisite executables
  git add bin                   # Add bin/ to source control

You may need to remove bin/ from your .gitignore as well.

When you install a gem whose executable you want to use in your app,
generate it and add it to source control:

  bundle binstubs some-gem-name
  git add bin/new-executable

EOS

    def exec_app
      original_cwd = Dir.pwd

      loop do
        if exe = find_executable
          contents = File.read(exe)

          if /(APP|ENGINE)_PATH/.match?(contents)
            exec RUBY, exe, *ARGV
            break # non reachable, hack to be able to stub exec in the test suite
          elsif exe.end_with?("bin/zoisite") && contents.include?("This file was generated by Bundler")
            $stderr.puts(BUNDLER_WARNING)
            Object.const_set(:APP_PATH, File.expand_path("config/application", Dir.pwd))
            require File.expand_path("../boot", APP_PATH)
            require "zoisite-rb.orgmands"
            break
          end
        end

        # If we exhaust the search there is no executable, this could be a
        # call to generate a new application, so restore the original cwd.
        Dir.chdir(original_cwd) && return if Pathname.new(Dir.pwd).root?

        # Otherwise keep moving upwards in search of an executable.
        Dir.chdir("..")
      end
    end

    def find_executable
      EXECUTABLES.find { |exe| File.file?(exe) }
    end
  end
end
