# frozen_string_literal: true

require "zoisite/generators"

module Zoisite
  module Command
    class DestroyCommand < Base # :nodoc:
      no_commands do
        def help
          boot_application!
          load_generators

          Zoisite::Generators.help self.class.command_name
        end
      end

      desc "destroy GENERATOR", "Remove code generated by `bin/zoisite generate`"
      def perform(*)
        generator = args.shift
        return help unless generator

        boot_application!
        load_generators

        Zoisite::Generators.invoke generator, args, behavior: :revoke, destination_root: Zoisite::Command.root
      end
    end
  end
end
